blank_issues_enabled: true
contact_links:
  - name: Get support on Discord
    url: https://discord.gg/EXqV7W8MtY
    about: Get help from the maintainers on Discord
  - name: Feature request
    url: https://github.com/Brain-Bones/skeleton/discussions/new
    about: Request new feature
  - name: Ask a question, give feedback, share your project
    url: https://github.com/Brain-Bones/skeleton/discussions
    about: Connect with other community members with GitHub discussions