name: Report an issue with Skeleton docs
description: See a typo? Outdated types? File a docs issue here!
labels: 'documentation'
body:
- type: markdown
  attributes:
    label: Sometimes something slips through the cracks, and the documentation isn't quite right. Thanks for letting us know!
- type: input
  id: link
  attributes:
    label: Link to the page with the error
- type: textarea
  id: quote
  attributes:
    label: What's wrong with it?
- type: dropdown
  id: participate
  attributes:
    label: Are you able to create a Pull Request with the fix?
    options:
      - 'Yes'
      - 'No'
